# Generated by Django 2.2.3 on 2019-07-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190706_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.ManyToManyField(related_name='events', to='events.Type'),
        ),
    ]
