# Generated by Django 2.2.3 on 2019-07-06 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20190706_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='types',
        ),
        migrations.AddField(
            model_name='event',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.Type'),
        ),
    ]
