# Generated by Django 2.2.3 on 2019-07-06 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20190706_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='login',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='repo',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
